title: Trousseau
logo: /assets/img/android-chrome-192x192.png
description: Store & access Secrets the Kubernetes way
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme 
theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://github.com/Trousseau-io/trousseau/zipball/main
  tar_url: https://github.com/Trousseau-io/trousseau/tarball/main
  repository_url: https://github.com/Trousseau-io
