#theme: jekyll-theme-hacker
theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Trousseau
logo: /assets/img/logo.jpeg
description: Secure and access your Kubernetes secrets and more
