#theme: jekyll-theme-hacker
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Trousseau
logo: /assets/img/logo.jpeg
description: Secure and access your Kubernetes secrets and more
